Controllers/ChatsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFirstSteps.Models;

namespace ProjectFirstSteps.Controllers
{
    public class ChatsController : Controller
    {
        private readonly MyContext _context;
        private string thisUser;

        public ChatsController(MyContext context)
        {
            _context = context;
            //thisUser = new MembresController(_context).thisUser;
        }

        // GET: Chats
        public IActionResult Index()
        {
            //ICollection<Membre> amis = new MembresController(_context).GetAmis();

            thisUser = HttpContext.Session.GetString("email");
            List<MembreMembre> amitie = _context.MembreMembres.Where(m => m.MailMembre1 == thisUser || m.MailMembre2 == thisUser).ToList();
            // return View(amitie);
            List<Membre> amis = new();
            foreach (var item in amitie)
            {
                if (item.MailMembre2 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre1));
                }
                else if (item.MailMembre1 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre2));
                }
            }

            return View(amis);
        }

        // GET: Chats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chat == null)
            {
                return NotFound();
            }

            return View(chat);
        }

        // GET: Chats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MailMembre1,MailMembre2,MessageDate,Containt")] Chat chat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chat);
        }

        // GET: Chats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats.FindAsync(id);
            if (chat == null)
            {
                return NotFound();
            }
            return View(chat);
        }

        // POST: Chats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MailMembre1,MailMembre2,MessageDate,Containt")] Chat chat)
        {
            if (id != chat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChatExists(chat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chat);
        }

        // GET: Chats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chat == null)
            {
                return NotFound();
            }

            return View(chat);
        }

        // POST: Chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chat = await _context.Chats.FindAsync(id);
            _context.Chats.Remove(chat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Here Emmanuel's Codes

        public async Task<IActionResult> PrivateChat(string mail, string search)
        {
            thisUser = HttpContext.Session.GetString("email");
            if (mail == string.Empty || mail == thisUser)
            {
                return NotFound();
            }

            if (search != null)
            {
                Chat newChat = new(thisUser, mail, search);
                _context.Chats.Add(newChat);
                _context.SaveChanges();
            }

            List<Chat> chats = await _context.Chats
                .Where(m => (m.MailMembre2 == thisUser && m.MailMembre1 == mail) || (m.MailMembre2 == mail && m.MailMembre1 == thisUser))
                .OrderBy(m => m.MessageDate)
                .ToListAsync();

            Membre membre1 = _context.Membres.FirstOrDefault(m => m.Email == thisUser);
            ViewData["Membre1"] = membre1.Nom + " " + membre1.Prenom + " ";
            Membre membre2 = _context.Membres.FirstOrDefault(m => m.Email == mail);
            ViewData["Membre2"] = membre2.Nom + " " + membre2.Prenom + " ";
            ViewData["MailMembre2"] = membre2.Email;

            ViewData["thisUser"] = thisUser;

            return View(chats);
        }

        private bool ChatExists(int id)
        {
            return _context.Chats.Any(e => e.Id == id);
        }

    }
}

Controllers/LiensController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFirstSteps.Models;

namespace ProjectFirstSteps.Controllers
{
    public class LiensController : Controller
    {
        private readonly MyContext _context;

        public LiensController(MyContext context)
        {
            _context = context;
        }

        // GET: Liens
        public async Task<IActionResult> Index()
        {
            return View(await _context.Liens.ToListAsync());
        }

        // GET: Liens/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Liens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lien == null)
            {
                return NotFound();
            }

            return View(lien);
        }

        // GET: Liens/Create
        public IActionResult Create()
        {
            Lien lien = new Lien();
            return PartialView("_Lien",lien);
        }

        // POST: Liens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Url,Id,nomRessource")] Lien lien)
        {
            if (ModelState.IsValid)
            {
                var EmailSession = HttpContext.Session.GetString("email");
                _context.Add(lien);
                Publication publication = new Publication
                {
                    dateDePublication = DateTime.Now,
                    Ressource = lien,
                    Membre = _context.Membres.Find(EmailSession)
                };
                _context.Add(publication);
                PersonalizedClass personalized = new PersonalizedClass
                {
                    UserName = User.Identity.Name,
                    UserMail = EmailSession,
                    PublicationDate = DateTime.Now,
                    RessourceName = lien.nomRessource,
                    Url = lien.Url
                };
                _context.Add(personalized);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            return View(lien);
        }

        // GET: Liens/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Liens.FindAsync(id);
            if (lien == null)
            {
                return NotFound();
            }
            return View(lien);
        }

        // POST: Liens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Url,Id,nomRessource")] Lien lien)
        {
            if (id != lien.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lien);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LienExists(lien.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lien);
        }

        // GET: Liens/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lien = await _context.Liens
                .FirstOrDefaultAsync(m => m.Id == id);
            if (lien == null)
            {
                return NotFound();
            }

            return View(lien);
        }

        // POST: Liens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lien = await _context.Liens.FindAsync(id);
            _context.Liens.Remove(lien);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LienExists(int id)
        {
            return _context.Liens.Any(e => e.Id == id);
        }
    }
}

Controllers/MessagesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFirstSteps.Models;

namespace ProjectFirstSteps.Controllers
{
    public class MessagesController : Controller
    {
        private readonly MyContext _context;

        public MessagesController(MyContext context)
        {
            _context = context;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
            return View(await _context.Messages.ToListAsync());
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            Message message = new Message();
            return PartialView("_MessagesPartial", message);
        }


        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("libelle,Id,nomRessource")] Message message)
        {
            if (ModelState.IsValid)
            {
                var EmailSession = HttpContext.Session.GetString("email");
                _context.Add(message);
                Publication publication = new Publication
                {
                    dateDePublication = DateTime.Now,
                    Ressource = message,
                    Membre = _context.Membres.Find(EmailSession)
                };
                _context.Add(publication);
                PersonalizedClass personalized = new PersonalizedClass
                {
                    UserName = User.Identity.Name,
                    UserMail = EmailSession,
                    PublicationDate = DateTime.Now,
                    RessourceName = message.nomRessource,
                    Libelle = message.libelle
                };
                _context.Add(personalized);
                await _context.SaveChangesAsync();
                ViewBag.Message = message;
                ViewBag.MessagePublication = publication;
                return RedirectToAction("Index","Home");
            }
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("libelle,Id,nomRessource")] Message message)
        {
            if (id != message.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var message = await _context.Messages.FindAsync(id);
            _context.Messages.Remove(message);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
            return _context.Messages.Any(e => e.Id == id);
        }
    }
}

Views/Home/Admin.cshtml
@model IEnumerable<ProjectFirstSteps.Models.Membre>


@{
    ViewData["Title"] = "Admin Page";
}

<div class="left">
					<a asp-action="MesPublications" asp-controller="Membres" class="profile">
						<div class="profile-picture">
							<img src="~/Medias/Images/PhotoProfil/pic1.png" alt="">
						</div>
						<div class="handle">
							<h4>@User.Identity.Name</h4>
							<p class="text-muted">
								@Context.Session.GetString("email")
							</p>
						</div>
					</a>

					<div class="sidebar">
						<a class="menu-item active">
							<span><i class="uil uil-sign-in-alt"></i></span><h3>Inscriptions en attente</h3>
						</a>
						<a class="menu-item" asp-action="Index" asp-controller="Membres">
							<span><i class="uil uil-users-alt"></i></span><h3>Liste des membres</h3>
						</a>
						<a class="menu-item" asp-action="ComptesABloquer" asp-controller="Membres">
							<span><i class="uil uil-trash-alt"></i></span><h3>Comptes à supprimer</h3>
						</a>
						
						<a class="menu-item" id="theme">
							<span><i class="uil uil-palette"></i></span><h3>Theme</h3>
						</a>
						<a class="menu-item">
							<span><i class="uil uil-setting"></i></span><h3>Settings</h3>
						</a>
					</div>
				</div>
				<div class="middle">
					<div class=feeds>
						<div class="feed">
							<table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Email)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Nom)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.Prenom)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model) {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Email)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Nom)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.Prenom)
                                            </td>
                                            <td>
                                                <a class="btn btn-success" asp-action="ValiderInscription" asp-controller="Membres" asp-route-id="@item.Email">Valider</a>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
						</div>
					</div>
				</div>

Views/Home/Index.cshtml
@model IEnumerable<ProjectFirstSteps.Models.PersonalizedClass>

@{
    ViewData["Title"] = "Home Page";
}

				<div class="left">
					<a asp-action="MesPublications" asp-controller="Membres" class="profile">
						<div class="profile-picture">
							<img src="~/Medias/Images/PhotoProfil/pic1.png" alt="">
						</div>
						<div class="handle">
							<h4>@User.Identity.Name</h4>
							<p class="text-muted">
								@Context.Session.GetString("email")
							</p>
						</div>
					</a>

					<div class="sidebar">
						<a class="menu-item active">
							<span><i class="uil uil-home"></i></span><h3>Acceuil</h3>
						</a>
							<a class="menu-item" asp-action="Amis" asp-controller="Membres">
								<span><i class="uil uil-users-alt"></i></span><h3>Amis</h3>
							</a>
						
						@if(User.IsInRole("Utilisateur")){
							<a class="menu-item" id="notifications" asp-action="ListeNotifications" asp-controller="Membres">
								<span><i class="uil uil-bell"><small class="notification-count">+</small></i></span><h3>Notifications</h3>
								<div class="notifications-popup">
								</div>
							</a>
							<a class="menu-item" id="messages-notifications" asp-action="Index" asp-controller="Chats">
								<span><i class="uil uil-envelope-alt"><small class="notification-count">3</small></i></span><h3>Messages</h3>
							</a>
						}
						@if(User.IsInRole("Moderateur")){
							<a class="menu-item" asp-action="Index" asp-controller="Membres">
								<span><i class="uil uil-users-alt"></i></span><h3>Liste des Membres</h3>
							</a>
						}
						@if(User.IsInRole("Administrateur")){
							<a asp-action="Admin" class="menu-item">
								<span><i class="uil uil-dashboard"></i></span><h3>Espace Administrateur</h3>
							</a>
						}
						<a class="menu-item" id="theme">
							<span><i class="uil uil-palette"></i></span><h3>Theme</h3>
						</a>
						<a class="menu-item" asp-action="Edit" asp-controller="Membres" asp-route-id="@Context.Session.GetString("email")">
							<span><i class="uil uil-setting"></i></span><h3>Settings</h3>
						</a>
							
					</div>
						<button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addPhotoVideo" 
						data-url="@Url.Action("Create","PhotoVideos")">Publication</button>
				</div>
				
				<div class="middle">
					<div class="create-post">
						<div class="profile-picture">
							<img alt="" src="~/Medias/Images/PhotoProfil/pic2.jpg">
						</div>
						<input type="text" placeholder="What's new?" id="create-post">
						<div>
							<div id ="addPublication" ></div>
							<button style="margin-right:1rem" type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addUrl" 
							data-url="@Url.Action("Create","Liens")"><i class="uil uil-link"></i></button>
						</div>
						<div>
							<div id ="addPublication" ></div>
							<button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addMessage" 
							data-url="@Url.Action("Create","Messages")"><i class="uil uil-message"></i></button>
						</div>
					</div>
					

					<div class="feeds">
						@foreach (var item in Model.OrderByDescending(item => item.PublicationDate))
						{
							<div class="feed">
								<div class="head">
									<div class="user">
										<div class="profile-picture">
											<img src="~/Medias/Images/PhotoProfil/pic4.png" alt="">
										</div>
										<div class="ingo">
											<h3>@Html.DisplayFor(modelItem => item.UserName)</h3>
											<small>@Html.DisplayFor(modelItem => item.PublicationDate)</small>
										</div>
									</div>
									<span class="edit">
										<i class="uil uil-ellipsis-h"></i>
									</span>
								</div>
								@if(item.Libelle != null){
									<div>
										<p>@Html.DisplayFor(modelItem => item.Libelle)</p>
									</div>
								}
								@if(item.Url != null){
									<div>
										<a href="@Html.DisplayFor(modelItem => item.Url)" target="_blank">@Html.DisplayFor(modelItem => item.Url)</a>
									</div>
								}
								@if(item.Legende != null){
									<p>@Html.DisplayFor(modelItem => item.Legende)</p>
									@if(item.type == 1)
									{
										<div class="photo">
											<img src="@Html.DisplayFor(modelItem => item.Path)" alt="" loading="lazy">
										</div>
									}
									@if(item.type == 2)
									{
										<div class="photo">
											<video src="@Html.DisplayFor(modelItem => item.Path)" controls preload="none" width=500 height=400 ></video>
										</div>
									}

								}
								<div class="action-button">
									<div class="interaction-buttons">
										<span><i class="uil uil-heart"></i></span>
										<span><i class="uil uil-comment-dots"></i></span>
										<span><i class="uil uil-share-alt"></i></span>
									</div>
								<div class="bookmarks">
									<span><i class="uil uil-bookmark-full"></i></span>
								</div>
							</div>
							<div class="liked-by">
								<span><img src="~/Medias/Images/PhotoProfil/pic1.png"></span>
								<span><img src="~/Medias/Images/PhotoProfil/pic2.jpg"></span>
								<span><img src="~/Medias/Images/PhotoProfil/pic3.png"></span>
								<p>Liked by <b>ErnesArnold</b> and <b>2,450 others</b></p>
							</div>
							<div class="caption">
								<p><b>Alfred 06</b> Lorem ipsum dolor sit amet consectetur adipisicing elit.
									Illum...</p>
							</div>
							<div class="comments text-muted">View all 276 comments</div>
							</div>
						}
						
						<!-------------END OF FEED---------->

					</div>
				</div>
				<div class="right">
					<div class="messages">
						<div class="heading">
							<h4>Messages</h4><i class="uil uil-edit"></i>
						</div>
						<div class="search-bar">
							<i class="uil uil-search"></i>
							<input type="search" placeholder="Search Messages" id="message-search">
						</div>
						<div class="category">
							<h6 class="active">Primary</h6>
							<h6>General</h6>
							<h6 class="message-requests">Request(7)</h6>
						</div>
						<div class="message">
							<div class="profile-picture">
								<img src="~/Medias/Images/PhotoProfil/pic4.png" alt="">
								<div class="active"></div>
							</div>
							<div class="message-body">
								<h5>Edem Quist</h5>
								<p class="text-muted">Juste woke up man</p>
							</div>
						</div>
						<div class="message">
							<div class="profile-picture">
								<img src="~/Medias/Images/PhotoProfil/pic1.png" alt="">
								<div class="active"></div>
							</div>
							<div class="message-body">
								<h5>J Martins</h5>
								<p class="text-muted">Thanks you bro✌</p>
							</div>
						</div>
						<div class="message">
							<div class="profile-picture">
								<img src="~/Medias/Images/PhotoProfil/pic3.png" alt="">
								<div class="active"></div>
							</div>
							<div class="message-body">
								<h5>Irai Aoro</h5>
								<p class="text-muted">Hi,😙 how are you doing?</p>
							</div>
						</div>
						<div class="message">
							<div class="profile-picture">
								<img src="~/Medias/Images/PhotoProfil/pic4.png" alt="">
								<div class="active"></div>
							</div>
							<div class="message-body">
								<h5>Grid Swallow</h5>
								<p class="text-muted">Happy Birthday man!😎</p>
							</div>
						</div>
						<div class="message">
							<div class="profile-picture">
								<img src="~/Medias/Images/PhotoProfil/pic2.jpg" alt="">
								<div class="active"></div>
							</div>
							<div class="message-body">
								<h5>Edwige Blitz</h5>
								<p class="text-muted">Ara Ara!😊</p>
							</div>
						</div>
					</div>

					<div class="friend-requests">
						<h4>Requests</h4>
						<div class="request">
							<div class="info">
								<div class="profile-picture">
									<img alt="" src="~/Medias/Images/PhotoProfil/pic2.jpg">
								</div>
								<div>
									<h5>Tony Stark</h5>
									<p class="text-muted">8 mutual friends</p>
								</div>
							</div>
							<div class="action">
								<button class="btn btn-primary">Accept</button>
								<button class="btn">Refuse</button>
							</div>
						</div>

						<div class="request">
							<div class="info">
								<div class="profile-picture">
									<img alt="" src="~/Medias/Images/PhotoProfil/pic3.png">
								</div>
								<div>
									<h5>Naira Romakono</h5>
									<p class="text-muted">12 mutual friends</p>
								</div>
							</div>
							<div class="action">
								<button class="btn btn-primary">Accept</button>
								<button class="btn">Refuse</button>
							</div>
						</div>

						<div class="request">
							<div class="info">
								<div class="profile-picture">
									<img alt="" src="~/Medias/Images/PhotoProfil/pic1.png">
								</div>
								<div>
									<h5>Shrek Shrek</h5>
									<p class="text-muted">6 mutual friends</p>
								</div>
							</div>
							<div class="action">
								<button class="btn btn-primary">Accept</button>
								<button class="btn">Refuse</button>
							</div>
						</div>

					</div>
				</div>

Views/Home/IndexBefore.cshtml
@*@model IEnumerable<ProjectFirstSteps.Models.MakingPublications>
*@
@{
    ViewData["Title"] = "Home Page Second";
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

@*<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Welcome @Context.Session.GetString("email")</p>
    <a asp-controller="Membres" asp-action="logout">Logout</a>
</div>*@

@*<form asp-controller="Messages" asp-action="Create">
    <input type="submit" value="Testing Publication" class="btn btn-primary">
</form>*@

@*<button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addMessage" 
data-url="@Url.Action("Create")">Create</button>*@

@*<div class="row" style="display:flex">

    <div style="margin-top:15px; margin-bottom:30px" class="col-3">
        <div id ="addPublication" ></div>
        <button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addMessage" 
        data-url="@Url.Action("Create","Messages")">Message</button>
    </div>

    <div class="col-3" style="margin-top:15px;">
        <div id ="addPublication" ></div>
        <button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addUrl" 
        data-url="@Url.Action("Create","Liens")">Url</button>
    </div>

    <div class="col-3" style="margin-top:15px;">
        <div id ="addPublication" ></div>
        <button type="button" class="btn btn-primary" data-toogle="ajax-modal" data-target="#addPhotoVideo" 
        data-url="@Url.Action("Create","PhotoVideos")">Photo / Video</button>
    </div>

</div>*@
@*<script type="text/javascript">
    
    $(document).ready(function () {
    $('.btn').click(function () {
        var url = $('#addMessage').data('url');
        $.get(url, function (data) {
            $("#addMessage").html(data);
            $("#addMessage").modal('show');
        });
    });
    });

    $(document).ready(function () {
    $('.btn').click(function () {
        var url = $('#addUrl').data('url');
        $.get(url, function (data) {
            $("#addUrl").html(data);
            $("#addUrl").modal('show');
        });
    });
    });

    $(document).ready(function () {
    $('.btn-block').click(function () {
        var url = $('#addPhotoVideo').data('url');
        $.get(url, function (data) {
            $("#addPhotoVideo").html(data);
            $("#addPhotoVideo").modal('show');
        });
    });
    });
</script>*@