Models/Chat.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjectFirstSteps.Models
{
    public class Chat
    {
        
        public int Id { get; set; }

        public string MailMembre1 { get; set; }
        public string MailMembre2 { get; set; }

        public DateTime MessageDate { get; set; }
        public string Containt { get; set; }

        public Chat(string Mail1, string Mail2, string containt)
        {
            this.MailMembre1 = Mail1;
            this.MailMembre2 = Mail2;
            this.Containt = containt;
            this.MessageDate = DateTime.Now;
        }

        public Chat()
        {

        }

    }
}

Controllers/ChatsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFirstSteps.Models;

namespace ProjectFirstSteps.Controllers
{
    public class ChatsController : Controller
    {
        private readonly MyContext _context;
        private string thisUser;

        public ChatsController(MyContext context)
        {
            _context = context;
            //thisUser = new MembresController(_context).thisUser;
        }

        // GET: Chats
        public IActionResult Index()
        {
            //ICollection<Membre> amis = new MembresController(_context).GetAmis();

            thisUser = HttpContext.Session.GetString("email");
            List<MembreMembre> amitie = _context.MembreMembres.Where(m => m.MailMembre1 == thisUser || m.MailMembre2 == thisUser).ToList();
            // return View(amitie);
            List<Membre> amis = new();
            foreach (var item in amitie)
            {
                if (item.MailMembre2 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre1));
                }
                else if (item.MailMembre1 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre2));
                }
            }

            return View(amis);
        }

        // GET: Chats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chat == null)
            {
                return NotFound();
            }

            return View(chat);
        }

        // GET: Chats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Chats/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,MailMembre1,MailMembre2,MessageDate,Containt")] Chat chat)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chat);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chat);
        }

        // GET: Chats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats.FindAsync(id);
            if (chat == null)
            {
                return NotFound();
            }
            return View(chat);
        }

        // POST: Chats/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,MailMembre1,MailMembre2,MessageDate,Containt")] Chat chat)
        {
            if (id != chat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChatExists(chat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chat);
        }

        // GET: Chats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chat = await _context.Chats
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chat == null)
            {
                return NotFound();
            }

            return View(chat);
        }

        // POST: Chats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chat = await _context.Chats.FindAsync(id);
            _context.Chats.Remove(chat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Here Emmanuel's Codes

        public async Task<IActionResult> PrivateChat(string mail, string search)
        {
            thisUser = HttpContext.Session.GetString("email");
            if (mail == string.Empty || mail == thisUser)
            {
                return NotFound();
            }

            if (search != null)
            {
                Chat newChat = new(thisUser, mail, search);
                _context.Chats.Add(newChat);
                _context.SaveChanges();
            }

            List<Chat> chats = await _context.Chats
                .Where(m => (m.MailMembre2 == thisUser && m.MailMembre1 == mail) || (m.MailMembre2 == mail && m.MailMembre1 == thisUser))
                .OrderBy(m => m.MessageDate)
                .ToListAsync();

            Membre membre1 = _context.Membres.FirstOrDefault(m => m.Email == thisUser);
            ViewData["Membre1"] = membre1.Nom + " " + membre1.Prenom + " ";
            Membre membre2 = _context.Membres.FirstOrDefault(m => m.Email == mail);
            ViewData["Membre2"] = membre2.Nom + " " + membre2.Prenom + " ";
            ViewData["MailMembre2"] = membre2.Email;

            ViewData["thisUser"] = thisUser;

            return View(chats);
        }

        private bool ChatExists(int id)
        {
            return _context.Chats.Any(e => e.Id == id);
        }

    }
}

Controllers/MembresController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectFirstSteps.Models;

namespace ProjectFirstSteps.Controllers
{
    public class MembresController : Controller
    {
        private readonly MyContext _context;
        public string thisUser = "";
        //public static List<Claim> claims = ClaimsPrincipal.Current.Identities.First().Claims.ToList();
        //public string thisUser = claims?.FirstOrDefault(x => x.Type.Equals("Email", StringComparison.OrdinalIgnoreCase))?.Value;

        public MembresController(MyContext context)
        {
            //var thisUser = HttpContext.Session.GetString("email");
            var thisUser = "";
            _context = context;
            
            //Here Emmanuel Codes

            List<MembreMembre> amitie = _context.MembreMembres.Where(m => m.MailMembre1 == thisUser || m.MailMembre2 == thisUser).ToList();
            // return View(amitie);
            List<Membre> amis = new();
            foreach (var item in amitie)
            {
                if (item.MailMembre2 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre1));
                }
                else if (item.MailMembre1 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre2));
                }
            }
        }

        public ICollection<Membre> GetAmis()
        {
            var thisUser = HttpContext.Session.GetString("email");
            List<MembreMembre> amitie = _context.MembreMembres.Where(m => m.MailMembre1 == thisUser || m.MailMembre2 == thisUser).ToList();
            // return View(amitie);
            List<Membre> amis = new();
            foreach (var item in amitie)
            {
                if (item.MailMembre2 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre1));
                }
                else if (item.MailMembre1 == thisUser)
                {
                    amis.Add(_context.Membres.FirstOrDefault(m => m.Email == item.MailMembre2));
                }
            }

            return amis;
        }

        public IActionResult Welcome()
        {
            return View();
        }

        // GET: Publications
        public async Task<IActionResult> MesPublications()
        {
            return View("MesPublications",await _context.Personalizeds.ToListAsync());
        }

        //Recuperer les notifications en passant le mail de l'utilisateur en parametre
        public async Task<IActionResult> PublicationsParam(string id)
        {
            var model = await _context.Personalizeds.Where(m => m.UserMail == id).OrderByDescending(i => i.PublicationDate).ToListAsync();
            return View("NewView", model);
        }

        public async Task <IActionResult> Signaler(int id)
        {
            var publication = await _context.Personalizeds.Where(m => m.Id == id).SingleOrDefaultAsync();
            return View(publication);
        }

        [HttpPost, ActionName("Signaler")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignalerConfirmed(int id)
        {
            var notification = new Notifications
            {
                Contenu = "Votre publication a été signalée. Veuillez vous conformer aux conditions d'utilisation de NetAtlas.",
                MembreEmail = await _context.Personalizeds.Where(i => i.Id == id).Select(e => e.UserMail).FirstOrDefaultAsync(),
                PersonalizedClass = await _context.Personalizeds.FindAsync(id),
                IsAdvertisement = true
            };
            _context.Add(notification);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> ListeNotifications()
        {
            var EmailSession = HttpContext.Session.GetString("email");
            var notifications = await _context.Notifications
                .Where(m => m.MembreEmail == EmailSession)
                .Include(p => p.PersonalizedClass).ToListAsync();
            return View(notifications);
        }

        public IActionResult ValiderInscription(string id)
        {
            var membre = _context.Membres.Find(id);
            membre.IsActivated = true;
            Notifications notifications = new Notifications
            {
                Contenu = "Votre inscription a été validée. Bienvenue sur NetAtlas!",
                Membre = membre,
            };
            _context.Add(notifications);
            _context.SaveChanges();
            return RedirectToAction("Admin","Home");
        }

        //Recuperer la liste des membres signalés 3 fois (au moins)
        public IActionResult ComptesABloquer()
        {
            List<object> liste = new List<object>();
            var listeEmail = _context.Notifications.Select(e => e.MembreEmail).ToList();
            var groupe = listeEmail.GroupBy(i => i);
            foreach(var item in groupe)
            {
                if(item.Count() > 2)
                {
                    liste.Add(item.Key);
                }
            }
            ViewBag.mails = liste;
            return View();
        }

        public async Task<IActionResult> Reinitialiser(string id)
        {
            var invitations = await _context.Invitations.Where(e => e.InviterMail == id || e.InvitedMail == id).ToListAsync();
            var membremembre = await _context.MembreMembres.Where(m => m.MailMembre1 == id || m.MailMembre2 == id).ToListAsync();
            var chats = await _context.Chats.Where(c => c.MailMembre1 == id || c.MailMembre2 == id).ToListAsync();

            _context.Invitations.RemoveRange(invitations);
            _context.MembreMembres.RemoveRange(membremembre);
            _context.Chats.RemoveRange(chats);

            var notifications = await _context.Notifications.Where(n => n.MembreEmail == id).ToListAsync();
            var personalizedClass = await _context.Personalizeds.Where(p => p.UserMail == id).ToListAsync();
            var publications = await _context.Publications.Where(p => p.Membre.Email ==  id).ToListAsync();

            if (notifications != null)
            {
                _context.Notifications.RemoveRange(notifications);
            }
            _context.Personalizeds.RemoveRange(personalizedClass);
            _context.Publications.RemoveRange(publications);

            Notifications notification = new Notifications
            {
                Contenu = "Votre compte a été réinitialisé par un administrateur.",
                Membre = _context.Membres.Where(m => m.Email == id).Single()
            };
            _context.Add(notification);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Membres
        [Authorize(Roles = "Moderateur,Administrateur")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Membres.Include(r => r.Role).ToListAsync());
        }

        // GET: Membres/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres
                .FirstOrDefaultAsync(m => m.Email == id);
            if (membre == null)
            {
                return NotFound();
            }

            return View(membre);
        }

        // GET: Membres/Create
        //[Authorize(Roles = "Administrateur")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Membres/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Email,Nom,Prenom,Password,Role")] Membre membre)
        {

            if (ModelState.IsValid)
            {
                var isExist = IsEmailExist(membre.Email);
                if (isExist)
                {
                    ModelState.AddModelError("EmailExist", "This email already exists, try another one");
                    return View(membre);
                }
                else
                {
                    membre.Password = Encryption.Hash(membre.Password);
                    membre.Role = _context.Roles.Where(a => a.Name == "Utilisateur").FirstOrDefault();
                    _context.Add(membre);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Welcome));
                }
            }
            return View(membre);
        }

        // GET: Membres/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var membre = await _context.Membres.FindAsync(id);
            if (membre == null)
            {
                return NotFound();
            }
            return View(membre);
        }

        // POST: Membres/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Views/Chats/Create.cshtml
@model ProjectFirstSteps.Models.Chat

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Chat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MailMembre1" class="control-label"></label>
                <input asp-for="MailMembre1" class="form-control" />
                <span asp-validation-for="MailMembre1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MailMembre2" class="control-label"></label>
                <input asp-for="MailMembre2" class="form-control" />
                <span asp-validation-for="MailMembre2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MessageDate" class="control-label"></label>
                <input asp-for="MessageDate" class="form-control" />
                <span asp-validation-for="MessageDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Containt" class="control-label"></label>
                <input asp-for="Containt" class="form-control" />
                <span asp-validation-for="Containt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Chats/Delete.cshtml
@model ProjectFirstSteps.Models.Chat

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Chat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MailMembre1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MailMembre1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MailMembre2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MailMembre2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Containt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Containt)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Chats/Details.cshtml
@model ProjectFirstSteps.Models.Chat

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Chat</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MailMembre1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MailMembre1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MailMembre2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MailMembre2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MessageDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MessageDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Containt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Containt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Chats/Edit.cshtml
@model ProjectFirstSteps.Models.Chat

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Chat</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MailMembre1" class="control-label"></label>
                <input asp-for="MailMembre1" class="form-control" />
                <span asp-validation-for="MailMembre1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MailMembre2" class="control-label"></label>
                <input asp-for="MailMembre2" class="form-control" />
                <span asp-validation-for="MailMembre2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MessageDate" class="control-label"></label>
                <input asp-for="MessageDate" class="form-control" />
                <span asp-validation-for="MessageDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Containt" class="control-label"></label>
                <input asp-for="Containt" class="form-control" />
                <span asp-validation-for="Containt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Chats/Index.cshtml
@model IEnumerable<ProjectFirstSteps.Models.Membre>

@{
    ViewData["Title"] = "Chat";
    Layout = "~/Views/Shared/_LayoutAmis.cshtml";
}

<h2>Choisissez un ami avec qui discuter</h2>
<div class="post-container">
    
    @using(Html.BeginForm("Amis", "Membres", FormMethod.Get))
    {
        @Html.TextBox("search") <input type="submit" value="Rechercher"/>
    }
    <hr />
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Nom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Prenom)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @if (Model.Count() != 0)
    {
        @foreach (var item in Model) {
                <tr>
                
                    <td>
                        @Html.DisplayFor(modelItem => item.Nom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Prenom)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-mail="@item.Email">Edit</a> |
                        <a asp-action="Details" asp-route-mail="@item.Email">Details</a> |
                        <a asp-controller="Chats" asp-action="PrivateChat" asp-route-mail="@item.Email">Message</a>
                    </td>
                
                </tr>
        }

    }
    @if(Model.Count() == 0)
    {
        <script>
            alert("Aucun élément trouvé");
        </script>
    }
        </tbody>
    </table>
</div>

Views/Chats/PrivateChat.cshtml
@model IEnumerable<ProjectFirstSteps.Models.Chat>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MailMembre1)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MessageDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Containt)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
                <td>
                    @{
                        if (ViewData["thisUser"].Equals(item.MailMembre1))
                        {
                            @Html.ViewData["Membre1"];
                        }
                        else
                        {
                            @Html.ViewData["Membre2"];
                        }
                    }
                
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MessageDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Containt)
            </td>
            <td>
               <!-- <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | --> 
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>









<!--
<div class="row">
    <div class="col-md-4">
        <form asp-action="Privatechat">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label for="Containt" class="control-label"></label>
                <input for="Containt" id="Containt" class="form-control" />
                <span  class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Envoyer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
-->

@using(Html.BeginForm("PrivateChat", "Chats", FormMethod.Get))
{
    @Html.TextBox("search") <input type="submit" asp-route-email="" value="Envoyer"/>
    @Html.TextBox("mail") <input type="hidden" value="@Html.ViewData["MailMembre2"];" />
}